name: "kubectl-actions"
description: "Github actions for automating kubectl commands."
branding:
  icon: "anchor"
  color: "blue"
inputs:
  args:
    description: "Arguments of kubectl"
    required: true
outputs:
  result:
    description: "Output of the kubectl command run"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.args }}
